services:
  - type: web
    name: backend
    root: server
    build_command: npm install
    start_command: npm start
    env:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - SUPABASE_SERVICE_ROLE_KEY
      - JWT_SECRET
      - FRONTEND_URL
      - NODE_ENV
      - PORT
    node_version: 18
