[build]
  command = "npm run build"
  publish = "build"
  base = "."

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/*"
  to = "https://gavshala-donation-server.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
